var fishData=[
 
    {
        imgUrl:"https://dao54xqhg9jfa.cloudfront.net/ProductMerchantdising/3b5b2bd4-d41a-8bd4-2a1e-fe5c571d2f84/original/1586376386.4432--2020-04-0901_36_26--472.jpeg?format=webp",
        name:"Freshwater Prawns 60Count/Kg (Jhinga/Seegadi)- Cleaned & Deveined, No Tail",
        des:"Freshwater Vannamei prawns. De-shelled, cleaned, deveined, butterflied prawns, with head and tail removed.",
        net_tag:"Net wt:",
        net:"250",
        gross_tag:"Gross:",
        gross:"500",
        unit:"gms",
        price_tag:"MRP:",
        cuurency:"₹",
        price:"349",
        strikePrice:"",
        off:"",
        off_tag:"%OFF",
    },
    {
        imgUrl:"https://dao54xqhg9jfa.cloudfront.net/ProductMerchantdising/edb7d551-80c1-888a-238b-282e8c19ebfd/original/1604229879.7734--2020-11-0116_54_39--738.jpeg?format=webp",
        name:"Freshwater Prawns 60Count/Kg (Jhinga/Seegadi) - Cleaned & Deveined, No Tail - Large pack",
        des:"Freshwater Vannamei prawns. De-shelled, cleaned, deveined, butterflied prawns, with head and tail removed.",
        net_tag:"Net wt:",
        net:"500",
        gross_tag:"Gross:",
        gross:"840",
        unit:"gms",
        price_tag:"MRP:",
        cuurency:"₹",
        price:"514",
        strikePrice:"685",
        off:"25",
        off_tag:"%OFF",
    },
   
    {
        imgUrl:"https://dao54xqhg9jfa.cloudfront.net/ProductMerchantdising/958f431a-9b65-3430-2c3e-90f5e3aed0d2/original/1599923920.2257--2020-09-1220_48_40--738.jpeg?format=webp",
        name:"Premium Mackerel (Bangda) Small - Whole, Cleaned",
        des:"Small-sized, gutted and cleaned Mackerel with head and tail intact, defined by its taut flesh.",
        net_tag:"Net wt:",
        net:"500",
        gross_tag:"Gross:",
        gross:"650",
        unit:"gms",
        price_tag:"MRP:",
        cuurency:"₹",
        price:"249",
        strikePrice:"",
        off:"",
        off_tag:"%OFF",
    },
    {
        imgUrl:"https://dao54xqhg9jfa.cloudfront.net/ProductMerchantdising/88e3d5b5-577e-d773-41b7-54ad354dbc41/original/1587014153.978--2020-04-1610_45_53--738.jpeg?format=webp",
        name:"Rohu (Rui) Small - Bengali Cut, No Head",
        des:"Freshwater fish, small sized, cleaned & cut, without head, bengali cut",
        net_tag:"Net wt:",
        net:"500",
        gross_tag:"Gross:",
        gross:"700",
        unit:"gms",
        price_tag:"MRP:",
        cuurency:"₹",
        price:"219",
        strikePrice:"",
        off:"",
        off_tag:"%OFF",

    },
    {
        imgUrl:"https://d2407na1z3fc0t.cloudfront.net/prodDev/pr_m7wku6qrrv7/1/prod_display_image/1633173713.6231--2021-10-0216:51:53--1818",
        name:"Indian Salmon (Rawas) Medium - Steaks",
        des:"Omega 3 rich, low fat, white-fleshed, mild tasting Indian salmon crafted into meaty slabs.",
        net_tag:"Net wt:",
        net:"350",
        gross_tag:"Gross:",
        gross:"604",
        unit:"gms",
        price_tag:"MRP:",
        cuurency:"₹",
        price:"503",
        strikePrice:"629",
        off:"20",
        off_tag:"%OFF",
    },
    {
        imgUrl:"https://dao54xqhg9jfa.cloudfront.net/ProductMerchantdising/afaed7ac-e644-c411-d143-2eddce1a0a9e/original/1596201971.4611--2020-07-3118_56_11--738.jpeg?format=webp",
        name:"Sardine (Mathi) Small - Whole, Cleaned",
        des:"Small-sized, gutted and scaled silvery skinned, bony, oily fish with silken texture.",
        net_tag:"Net wt:",
        net:"500",
        gross_tag:"Gross:",
        gross:"600",
        unit:"gms",
        price_tag:"MRP:",
        cuurency:"₹",
        price:"224",
        strikePrice:"299",
        off:"25",
        off_tag:"%OFF",
    },
    {
        imgUrl:"https://d2407na1z3fc0t.cloudfront.net/prodDev/pr_3rkjm1v51mm/1/prod_display_image/1636890938.9032--2021-11-1417:25:38--905?format=webp",
        name:"Basa (Pangas) - Boneless Cubes",
        des:"Relish the smooth, soft texture of Indian Basa cubes in every bite.",
        net_tag:"Net wt:",
        net:"400",
        gross_tag:"Gross:",
        gross:"1600",
        unit:"gms",
        price_tag:"MRP:",
        cuurency:"₹",
        price:"395",
        strikePrice:"",
        off:"",
        off_tag:"%OFF",
    },
    {
        imgUrl:"https://dao54xqhg9jfa.cloudfront.net/ProductMerchantdising/edb7d551-80c1-888a-238b-282e8c19ebfd/original/1604229879.7734--2020-11-0116_54_39--738.jpeg?format=webp",
        name:"Freshwater Prawns 60Count/Kg (Jhinga/Seegadi) - Cleaned & Deveined, No Tail - Large pack",
        des:"Freshwater Vannamei prawns. De-shelled, cleaned, deveined, butterflied prawns, with head and tail removed.",
        net_tag:"Net wt:",
        net:"500",
        gross_tag:"Gross:",
        gross:"840",
        unit:"gms",
        price_tag:"MRP:",
        cuurency:"₹",
        price:"685",
        strikePrice:"",
        off:"",
        off_tag:"%OFF",
    },
    {
        imgUrl:"https://dao54xqhg9jfa.cloudfront.net/ProductMerchantdising/fb6dc0fc-ab1e-da1c-a66f-b74586cae631/original/1597861271.653--2020-08-1923_51_11--738.jpeg?format=webp",
        name:"Sea Bass (Barramundi/Bhetki) Medium - Curry Cut",
        des:"Curry cut of Sea Bass that is delicately textured with a subtle rich taste.",
        net_tag:"Net wt:",
        net:"350",
        gross_tag:"Gross:",
        gross:"637",
        unit:"gms",
        price_tag:"MRP:",
        cuurency:"₹",
        price:"449",
        strikePrice:"",
        off:"",
        off_tag:"%OFF",
    },
    {
        imgUrl:"https://d2407na1z3fc0t.cloudfront.net/prodDev/pr_nvvktwxg5of/1/prod_display_image/1633921452.0664--2021-10-1108:34:12--1818",
        name:"Basa (Pangus) - Finger Cut",
        des:"11-14 pieces of expertly crafted Basa fillet that’s further cut into long strips",
        net_tag:"Net wt:",
        net:"250",
        gross_tag:"Gross:",
        gross:"927",
        unit:"gms",
        price_tag:"MRP:",
        cuurency:"₹",
        price:"259",
        strikePrice:"",
        off:"",
        off_tag:"%OFF",
    },
    {
        imgUrl:"https://d2407na1z3fc0t.cloudfront.net/prodDev/pr_6j4jhm2si2y/1/prod_display_image/1611137119.5644--2021-01-2015:35:19--738?format=webp",
        name:"Rohu (Rui) - Head",
        des:"One medium, freshwater fish-head cleaned, cleaved in two and prepped for your next culinary adventure.",
        net_tag:"Net wt:",
        net:"1",
        gross_tag:"Gross:",
        gross:"1",
        unit:"gms",
        price_tag:"MRP:",
        cuurency:"₹",
        price:"49",
        strikePrice:"",
        off:"",
        off_tag:"%OFF",
    },
    {
        imgUrl:"https://dao54xqhg9jfa.cloudfront.net/ProductMerchantdising/3a949a58-9739-d71b-06f3-d6003290cf15/original/1596184869.2374--2020-07-3114_11_09--738.jpeg?format=webp",
        name:"Freshwater Large Prawns 30Count/Kg (Jhinga/Seegadi) - Cleaned & Deveined, No Tail",
        des:"Large butterflied prawns with head and tail removed - deshelled, cleaned, deveined.",
        net_tag:"Net wt:",
        net:"250",
        gross_tag:"Gross:",
        gross:"500",
        unit:"gms",
        price_tag:"MRP:",
        cuurency:"₹",
        price:"465",
        strikePrice:"",
        off:"",
        off_tag:"%OFF",
    },
    {
        imgUrl:"https://d2407na1z3fc0t.cloudfront.net/prodDev/pr_596601367dd0d/1/prod_display_image/1596215845.817--2020-07-3122:47:25--738?format=webp",
        name:"Sardine (Mathi) - Whole, Cleaned",
        des:"Gutted and scaled silvery skinned, sharp tasting, bony, oily fish with silken texture.",
        net_tag:"Net wt:",
        net:"500",
        gross_tag:"Gross:",
        gross:"714",
        unit:"gms",
        price_tag:"MRP:",
        cuurency:"₹",
        price:"385",
        strikePrice:"",
        off:"",
        off_tag:"%OFF",
    },
    {
        imgUrl:"https://d2407na1z3fc0t.cloudfront.net/prodDev/pr_6zckrc0k36h/1/prod_display_image/1629879664.7744--2021-08-2513:51:04--1818",
        name:"Black Pomfret (Paplet/Avoli/Chandi/Manji) Medium - Steaks",
        des:"Black Pomfret (Paplet/Avoli/Chandi/Manji) Medium - Steaks Flat, saltwater, dark skinned fish.",
        net_tag:"Net wt:",
        net:"300",
        gross_tag:"Gross:",
        gross:"704",
        unit:"gms",
        price_tag:"MRP:",
        cuurency:"₹",
        price:"549",
        strikePrice:"",
        off:"",
        off_tag:"%OFF",
    },
    {
        imgUrl:"https://d2407na1z3fc0t.cloudfront.net/prodDev/pr_8izjlf73pe9/1/prod_display_image/1608912991.3806--2020-12-2521:46:31--738?format=webp",
        name:"Seer (Vanjaram/Surmai) Medium - Curry Cut, No Head",
        des:"Perfectly curry-cut for flavoursome curries!",
        net_tag:"Net wt:",
        net:"500",
        gross_tag:"Gross:",
        gross:"640",
        unit:"gms",
        price_tag:"MRP:",
        cuurency:"₹",
        price:"755",
        strikePrice:"",
        off:"",
        off_tag:"%OFF",
    },
    {
        imgUrl:"https://d2407na1z3fc0t.cloudfront.net/prodDev/pr_6j4jhm298a5/1/prod_display_image/1634310717.0705--2021-10-1520:41:57--905?format=webp",
        name:"Parshe - Whole & Cleaned, No Tail",
        des:"Cleaned, gutted, prepped freshwater Parshe for the ultimate rustic Bengali comfort.",
        net_tag:"Net wt:",
        net:"500",
        gross_tag:"Gross:",
        gross:"793",
        unit:"gms",
        price_tag:"MRP:",
        cuurency:"₹",
        price:"375",
        strikePrice:"",
        off:"",
        off_tag:"%OFF",
    },
    {
        imgUrl:"https://dao54xqhg9jfa.cloudfront.net/ProductMerchantdising/975b51a5-bc81-e038-8491-e8b5e87a595a/original/1596217084.772--2020-07-3123_08_04--738.jpeg?format=webp",
        name:"Bata Small  - Whole, Cleaned",
        des:"Whole, cleaned, gutted, this Eastern favourite is now just a click away!",
        net_tag:"Net wt:",
        net:"250",
        gross_tag:"Gross:",
        gross:"340",
        unit:"gms",
        price_tag:"MRP:",
        cuurency:"₹",
        price:"203",
        strikePrice:"239",
        off:"15",
        off_tag:"%OFF",
    },
    {
        imgUrl:"https://d2407na1z3fc0t.cloudfront.net/prodDev/pr_9f7kk2nc6b8/1/prod_display_image/1624615050.2517--2021-06-2515:27:30--738",
        name:"Blue Crab (Nandu/Aedi) Medium - Whole, Cleaned",
        des:"Top shell removed and cleaned, Medium seawater crab with soft, sweet and succulent flesh",
        net_tag:"Net wt:",
        net:"500",
        gross_tag:"Gross:",
        gross:"800",
        unit:"gms",
        price_tag:"MRP:",
        cuurency:"₹",
        price:"699",
        strikePrice:"",
        off:"",
        off_tag:"%OFF",
    },
    {
        imgUrl:"https://d2407na1z3fc0t.cloudfront.net/prodDev/pr_fmnkgm7qc76/1/prod_display_image/1604569920.6197--2020-11-0515:22:00--738?format=webp",
        name:"Seer (Vanjaram/Surmai) Large - Boneless Cubes",
        des:"Smooth-textured seawater fish, in boneless cubes",
        net_tag:"Net wt:",
        net:"300",
        gross_tag:"Gross:",
        gross:"613",
        unit:"gms",
        price_tag:"MRP:",
        cuurency:"₹",
        price:"659",
        strikePrice:"",
        off:"",
        off_tag:"%OFF",
    },
    {
        imgUrl:"https://d2407na1z3fc0t.cloudfront.net/prodDev/pr_inpkaxvya2u/1/prod_display_image/1636890998.1006--2021-11-1417:26:38--905?format=webp",
        name:"Sea Bass (Barramundi/Bhetki) Medium - Boneless Cubes",
        des:"Bite into the juicy pinkish flesh of the Sea Bass crafted into delicious boneless cubes, perfect for frying.",
        net_tag:"Net wt:",
        net:"300",
        gross_tag:"Gross:",
        gross:"1070",
        unit:"gms",
        price_tag:"MRP:",
        cuurency:"₹",
        price:"759",
        strikePrice:"799",
        off:"5",
        off_tag:"%OFF",
    },
    {
        imgUrl:"https://dao54xqhg9jfa.cloudfront.net/OMS-ProductMerchantdising/520b3cad-7028-fcdb-73e2-f18c2f25fdbb/original/Tilapia+Tag.jpg?format=webp",
        name:"Tilapia (Jalebi) Small - Whole Cleaned & Gutted",
        des:"2-3 pieces of whole, mildly sweet freshwater fish",
        net_tag:"Net wt:",
        net:"500",
        gross_tag:"Gross:",
        gross:"685",
        unit:"gms",
        price_tag:"MRP:",
        cuurency:"₹",
        price:"203",
        strikePrice:"239",
        off:"15",
        off_tag:"%OFF",
    },
  
];
localStorage.setItem("fishdata",JSON.stringify(fishData));